# Generated by Django 3.2.18 on 2023-05-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_alter_receta_rentabilidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientereceta',
            options={'verbose_name': 'Insumos', 'verbose_name_plural': 'Listado de Insumos'},
        ),
        migrations.AddField(
            model_name='receta',
            name='CANTIDAD_PORCIONES',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='PRODUCTO',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='GASTOS_ADICIONALES',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22),
        ),
    ]
