# Generated by Django 3.2.18 on 2023-05-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0003_auto_20230505_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='COSTO_PORCION',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=22, null=True),
        ),
    ]
